Task2
ok-technopolis-2020/Ponomarev_Stepan pull request #2
Opened 2020-10-14 16:26 UTC by step-ponomarev

2020-10-14 16:27 UTC, step-ponomarev commented
Еще, конечно же даже близко не готово. Это я так, мало ли сразу замечания будут, что тянуть... ) ) ) ))))))

2020-10-14 16:41 UTC, fromanywhere requested changes

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +.input-area > .toggle-button {
А нужен ли такой хрупкий селектор?

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +ul.todo-list {
А зачем составной?

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +.todo-list > .todo-item:nth-child(1) {
псевдоклассы — хорошо, но лучше, когда без них

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +  > .todo-item:not():nth-child(1):not():nth-last-child(1):not():nth-last-child(2) {
Очень хрупко! Можно проще

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +  outline: none;
Фокусы оставляем все

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +  transition-duration: 200ms;
дюрейшн вижу, транзишена не вижу

2020-10-14 16:41 UTC, fromanywhere commented on styles/styles.css
> +.todo-item > input.complete-button:checked ~ .todo-text {
Да, что-то в таком духе и будет, это хорошо

2020-10-14 16:43 UTC, step-ponomarev commented on styles/styles.css
> +  > .todo-item:not():nth-child(1):not():nth-last-child(1):not():nth-last-child(2) {
Ой, я это не удалил...

2020-10-14 18:08 UTC, step-ponomarev commented on styles/styles.css
> +ul.todo-list {
Потому что я хочу отключить стандартное отображение только у этого списка, а не у всех списков вообще.

2020-10-14 18:08 UTC, step-ponomarev commented on styles/styles.css
> +ul.todo-list {
Потому что я хочу отключить стандартное отображение только у этого списка, а не у всех списков вообще.

2020-10-15 09:10 UTC, fromanywhere requested changes

2020-10-15 09:10 UTC, fromanywhere commented on styles/styles.css
> +  height: max-content;
зачем?

2020-10-15 09:10 UTC, fromanywhere commented on styles/styles.css
> +  transform: translate(-50%, -60%);
Гриды, флексы, — и тут же такие хаки с центрированием. Можно и аккуратнее!

2020-10-15 09:10 UTC, fromanywhere commented on styles/styles.css
> +  padding: 24.5px 17px 20px 17px;
это что, дробные пикселы?

2020-10-15 09:10 UTC, fromanywhere commented on styles/styles.css
> +  justify-self: center;
напрашивается space-between где-то в родителе

2020-10-15 14:14 UTC, step-ponomarev commented on styles/styles.css
> +  transform: translate(-50%, -60%);
Не хотелось делать сетку для body, что-то внутри говорит, что не нужно этого делать.

2020-10-23 12:25 UTC, fromanywhere requested changes

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  display: grid;
это хорошо

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  --grey-color: #cccccc;
отлично

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  z-index: 0;
зачем z-index?

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  margin-bottom: 17px;
это нехорошо. Заметно на фокусах, область клика не о чем: 
![image](https://user-images.githubusercontent.com/1042969/97000628-a9279a80-153f-11eb-82db-e365abe1b4ef.png)

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +.toggle-button::before,
Ага, а завтра дизайнер пришлет другую иконку, и как её?

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +.input-area > .input-field {
зачем такой селектор?

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  padding: 13px 11px;
![image](https://user-images.githubusercontent.com/1042969/97002338-88147900-1542-11eb-8014-c4cd747b355d.png)
левая часть съедается при переполнении

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  display: none;
потерялся переход по табу и читалки

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  transform: translate(-50%, -35%);
это зачем так

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  display: grid;
ну, нет, это компонент, не сетка, зачем грид тут

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  width: max-content;
зачем

2020-10-23 12:25 UTC, fromanywhere commented on styles/styles.css
> +  border: 1px solid var(--grey-color);
Прыгает 
![screencast 2020-10-23 15-20-49](https://user-images.githubusercontent.com/1042969/97003192-bd6d9680-1543-11eb-9e79-a7448de6aef6.gif)

2020-10-26 20:46 UTC, fromanywhere requested changes

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +ul.todo-list {
переходим на бэм

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  min-height: 64px;
Всё еще рвется 
![image](https://user-images.githubusercontent.com/1042969/97225680-00e63000-17e4-11eb-9a69-a8344dd5d99b.png)

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  display: block;
прыгает горизонталь
![screencast 2020-10-26 23-37-38](https://user-images.githubusercontent.com/1042969/97225983-6afed500-17e4-11eb-86d1-a2c8e81ae6fe.gif)

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  background-color: var(--hover-grey-color);
на фокус тогда наверное что-то тоже такое, с клавиатуры непонятно

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  outline-color: var(--outline-color);
Текст прилип 
![image](https://user-images.githubusercontent.com/1042969/97226155-a7cacc00-17e4-11eb-93bf-173e568c09e5.png)

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  width: 100%;
мне не очень нравится практика задавать на body размеры, потом оно обычно отстреливает, но допустим в нашем синтетическом примере пусть будет. Но ширина-то тут зачем

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +}
а где тени под формой?

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  width: 100%;
лучше flex-grow: 1;

2020-10-26 20:46 UTC, fromanywhere commented on styles/styles.css
> +  z-index: 1;
зачем?

2020-10-27 17:49 UTC, step-ponomarev commented on styles/styles.css
> +  min-height: 64px;
Вот сейчас не понял
<img width="809" alt="Снимок экрана 2020-10-27 в 20 48 08" src="https://user-images.githubusercontent.com/49997776/97341274-e5d3f880-1895-11eb-942b-1c67b85973ef.png">

2020-10-27 17:58 UTC, fromanywhere commented on styles/styles.css
> +  min-height: 64px;
в моем примере нет пробелов. И у юзеров не будет

2020-10-27 18:00 UTC, step-ponomarev commented on styles/styles.css
> +  min-height: 64px;
Эти юзеры... 
Вечно все портят!

2020-10-29 13:10 UTC, step-ponomarev commented on styles/styles.css
> +ul.todo-list {
Нужно соблюсти прям все нейминги вплоть до двойных подчеркиваний?

2020-10-29 13:45 UTC, fromanywhere commented on styles/styles.css
> +ul.todo-list {
в идеале да. Тренируем компонентное мышление

2020-10-29 13:52 UTC, fromanywhere commented on styles/styles.css
> +.control-pane > .clear-tasks-button {
с бэмом вот эти > уйдут везде

2020-10-29 13:53 UTC, fromanywhere commented on styles/styles.css
> +  display: inline;
что это за магия ) там просто абсолютами положить, и calc не нужен

2020-10-29 16:47 UTC, step-ponomarev commented on styles/styles.css
> +  display: inline;
Я вот думаю, вряд ли калками можно сильно производительность понизить, стоит ли их избегать, в каких кейсах это вообще это полезно?
Но тут они явно не нужны, согласен

2020-10-29 17:58 UTC, fromanywhere commented on styles/styles.css
> +  display: inline;
Ну, воообще да, считается, что сейчас это недорого. Просто у меня сохраняется субъективное мнение, что кальки подсвечивают беспомощность верстальщика, ну, потому что в целом они сделаны не для этого. Сейчас конечно их использую много чаще, чем раньше, именно из-за переменных — ну, мне кажется, вот там им и место, а лэйаут легко рисуется статикой и без них

2020-10-29 19:25 UTC, fromanywhere approved these changes
<img width="307" alt="approve" src="https://user-images.githubusercontent.com/1042969/97622635-9a585080-1a35-11eb-8f42-b9f2febdfce4.png">

2020-10-29 20:19 UTC, merged