Task3
ok-technopolis-2020/Ponomarev_Stepan pull request #3
Opened 2020-10-31 14:32 UTC by step-ponomarev

Нужно ли дробить еще сильнее стили?
И напомните плз зачем пост CSS нам, просто заменить селекторы на вложенность? Один синтаксис на другой?

2020-11-01 22:00 UTC, fromanywhere requested changes
> Нужно ли дробить еще сильнее стили?
> И напомните плз зачем пост CSS нам, просто заменить селекторы на вложенность? Один синтаксис на другой?

там в хедере чуть подробить а так норм
да, предлагается как минимум продемонстрировать способность прикрутить постцсс на примере postcss-nested , но можно поразвлекаться, автопрефиксер там заодно прикрутить

2020-11-01 22:00 UTC, fromanywhere commented on styles/header.css
> +.toggle-button {
ну нормально же всё с компонентным мышлением, чего всё в один файл-то

2020-11-01 22:00 UTC, fromanywhere commented on package.json
> +}
понятно что тут будет упоминание postcss-nested иначе как я у себя его разверну

2020-11-02 12:50 UTC, step-ponomarev commented on package.json
> +}
Чет он пока не хочет работать
<img width="1067" alt="Screenshot 2020-11-02 at 15 48 35" src="https://user-images.githubusercontent.com/49997776/97869830-2236a700-1d23-11eb-9024-88b7d87d6d9a.png">

2020-11-02 13:11 UTC, fromanywhere commented on package.json
> +}
А вот потому что на лекции было сказано, и в слайдах нарисовано, что ставим насильно 4ую версию

2020-11-02 13:16 UTC, step-ponomarev commented on package.json
> +}
Аформатив

2020-11-02 13:51 UTC, fromanywhere approved these changes
Ну ващет конечно подразумевалось не просто в package.json надпись добавить а типа, ну ладно, я проверил, оно работает
![image](https://user-images.githubusercontent.com/1042969/97875547-98d7a280-1d2b-11eb-96f3-398ade1c57a2.png)

2020-11-02 13:54 UTC, step-ponomarev commented
Я понимаю, позже сделаю.

2020-11-03 11:32 UTC, merged