Task4
ok-technopolis-2020/Ponomarev_Stepan pull request #4
Opened 2020-11-10 14:45 UTC by step-ponomarev

2020-11-18 16:39 UTC, fromanywhere requested changes

2020-11-18 16:39 UTC, fromanywhere commented on src/store/index.js
> +  get taskList() {
Итерация по ключам объекта не гарантирует порядок
`There is no guarantee that for...in will return the indexes in any particular order. ` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

2020-11-18 16:39 UTC, fromanywhere commented on src/view/taskListView.js
> +    this._taskList.removeChild(taskItem);
где-то тут надо бы снимать все события, которые были повешены

2020-11-18 16:39 UTC, fromanywhere commented on src/view/taskListView.js
> +      this._taskList.classList.add("todo-list_empty");
classList.toggle(classname, force)

2020-11-18 16:39 UTC, fromanywhere commented on src/helpers.js
> +  return `f${(~~(Math.random()*1e8)).toString(16)}`;
инкремент надежнее

2020-11-19 11:46 UTC, step-ponomarev commented on src/view/taskListView.js
> +    this._taskList.removeChild(taskItem);
<img width="595" alt="Screenshot 2020-11-19 at 14 42 43" src="https://user-images.githubusercontent.com/49997776/99661848-7e186400-2a75-11eb-926d-f43c4b417871.png">
Вообще да, сейчас добавил такую штуку. Но как мне очищать другие ивенты пока без понятия. Например удалять ивент с чек бокса после удаления. Рассматриваю 2 варианта: 
1) Сохранять все ивенты в объект какой-нибудь: Типа ID : Events
2) Вроде браузеры уже неплохо справляется с очисткой событий, или я ошибаюсь?

2020-11-19 11:52 UTC, fromanywhere commented on src/view/taskListView.js
> +    this._taskList.removeChild(taskItem);
1. Ивенты сохранять не надо. Нужен стандартный жизненный цикл компонента с инициализацией, получением дом-узлов, каким-то добавлением событий (есть разные способы упрощения жизни) и последующим удалением. Если сохраняются (или получаются заново, но это так себе) ссылки на узлы, проблемы не возникает

2. Дело не только в том, что тут какие-то домовые события, и гипотетически gc всё соберет. Тут может появиться какая-нибудь подписка на сторонний event bus, и как тогда?

2020-11-19 17:00 UTC, step-ponomarev commented on src/helpers.js
> +  return `f${(~~(Math.random()*1e8)).toString(16)}`;
Та вряд ли тут будут совпадения. Или о какой надежности идет речь.

2020-11-19 17:39 UTC, fromanywhere commented on src/helpers.js
> +  return `f${(~~(Math.random()*1e8)).toString(16)}`;
Ну, я на такое натыкался в жизни

2020-11-22 13:34 UTC, fromanywhere commented
А теперь самое интересное — мигрируем всё это на вебпак. У меня ушло два часа

2020-11-22 13:34 UTC, fromanywhere requested changes

2020-11-22 13:34 UTC, fromanywhere commented on assets/empty-list.svg
> +</g>
Ну тут какой-то мусор, но допустим это не суть

2020-11-22 13:34 UTC, fromanywhere commented on src/store/index.js
> +    this._allTaskAreCompleted = value;
зачем эта переменная?

2020-11-22 13:34 UTC, fromanywhere commented on src/view/addTaskFormView.js
> +export default addTaskFormView;
отучаемся от дефолтных экспортов по итогам лекции

2020-11-22 13:34 UTC, fromanywhere commented on src/view/taskListView.js
> +    const removeButtonOnClick = () => {
формально наверное с этим можно жить. Но по-хорошему конечно всё это должно быть иначе. Должен быть AbstractView c фабричными методами хотя бы destroy, от которого наследуются все вьюшки, и в этом методе заниматься отписками. Соответственно вьюшки вкладываются друг в друга, и при удалении вьюшки вложенные так же себя чистят. Потому что сейчас здесь в компонент элемента списка протекает логика атомарного компонента чекбокса, что вообще нездорово

2020-11-22 13:34 UTC, fromanywhere commented on src/store/index.js
> +  _saveTasks() {
тогда уже видимо и этот приватный

2020-11-22 13:34 UTC, fromanywhere commented on src/store/index.js
> +    this._tasks = [];
и тут приватные получаются

2020-11-22 13:40 UTC, step-ponomarev commented
Емае, вот так вот, да? Начинаем с простенького фриендли парсела, а теперь страдаем от вебпака?

2020-11-22 14:04 UTC, fromanywhere commented
> Емае, вот так вот, да? Начинаем с простенького фриендли парсела, а теперь страдаем от вебпака?

зато те студенты, которые не смогут закрыть лабу по js, хотя бы наскребут 4 за курс и получат общее представление. Таких 80% будет из группы. А без вебпака потом в реакт никак

2020-11-25 20:17 UTC, step-ponomarev commented on src/view/taskListView.js
> +    const removeButtonOnClick = () => {
Типа в конструктор прокидывать вьюшки?

2020-11-25 20:44 UTC, step-ponomarev commented on src/view/taskListView.js
> +    const removeButtonOnClick = () => {
Ну вот думаю, сделаю АбстрактнуюВьюшку с дестроем. Далее сделаю вьюшку, которая будет общей тип тудушкой. Внутрь вкладываю вьюшку со строкой добавлкния таски, вьюшку со списком задач(в котором создаются вьюшки таск айтемов(в которые нужно прокинуть методы)), вьюшку с панелью фильтров.

Правильно понял?

2020-11-25 20:55 UTC, step-ponomarev commented on src/view/taskListView.js
> +    const removeButtonOnClick = () => {
Ну и еще я айтемы списка сначала загоняю во фрагмент, а потом рендорю паком, если сделаю их отдельными классами(вьюшками), не получится срендерить все за раз. (Либо над поспать и подумтаь завтра :D)

2020-11-26 11:41 UTC, fromanywhere commented on src/view/taskListView.js
> +    const removeButtonOnClick = () => {
> Правильно понял?

Похоже что да, нормальное компонентное разбиение

Оптимизацию на фрагмент можно не делать, здесь сложно. Это мы так до виртуальных деревьев дойти можем

2020-11-27 10:24 UTC, fromanywhere requested changes

2020-11-27 10:24 UTC, fromanywhere commented on src/index.js
> +const addTaskFormView = new AddTaskFormView(onFormSubmit, onClickCompleteAll);
О, отлично, теперь это похоже на нормальные вьюшки. Но видно, что параметризуется каждая вьюшка разным сложным количеством аргументов, очевидно, что это так себе подход.

Теперь самое интересное — начинается заход на нормальный MVC

1) Раз у нас теперь есть вьюшки, которые вынесены по компонентам, то теперь своим рендером они в общем-то могут заниматься сами. Необходимость рендера, фактически, определяется изменениями в модели. Значит что теперь нужно сделать: взять шаблон «издатель-подписчик» и применить его к реализации. Издателем будет стор, подписчиками будут вьюшки, которые будут слушать поля этого стора.
Только мы возьмем не PubSub с именованными событиями, а Observer

Тут конечно надо бы по-хорошему делать так, чтобы все поля слушались отдельно, но это сложно, поэтому можно сэкономить, и пересоздавать элемент списка в массиве на произвольное изменение внутри него. Пересоздание приведет к бросанию события, вьюшка перерендерится

2) чтобы не заниматься инжектом обработчиков в каждое вью, вводим контроллер. Контроллер будет агрегировать в себе все методы работы над моделью. Тогда вызов метода контроллера вызовет модификацию модели, что повлечет ререндер вью. Вызов методов контроллера подвязан на пользовательский ввод, ура, мы получаем реактивное приложение.

Мы тут немного опережаем лекции — примерно на неделю, но это ничего. Значит что можно посмотреть про это: 

С точки зрения интерфейса версия на Java выглядит убедительнее https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B1%D0%BB%D1%8E%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

Есть классическая ссылка на паттерн, но на самом деле в реализации есть дырка :) https://addyosmani.com/resources/essentialjsdesignpatterns/book/#observerpatternjavascript

Лучше написать один раз свой и собрать все грабли, и знать, где оно потечет при отписках, чем качать готовое

2020-11-27 10:24 UTC, fromanywhere commented on src/view/abstractView.js
> +export class AbstractView {
по фану можно почитать про jsdoc

2020-11-27 15:16 UTC, step-ponomarev commented on src/index.js
> +const addTaskFormView = new AddTaskFormView(onFormSubmit, onClickCompleteAll);
> Но видно, что параметризуется каждая вьюшка разным сложным количеством аргументов
Прокидывать 1 объект с ивентами или инициализировать отдельно?

> Тут конечно надо бы по-хорошему делать так, чтобы все поля слушались отдельно
Типа двусторонний биндинг?

2020-11-27 15:45 UTC, fromanywhere commented on src/index.js
> +const addTaskFormView = new AddTaskFormView(onFormSubmit, onClickCompleteAll);
> Прокидывать 1 объект с ивентами или инициализировать отдельно?
Прокидывать инстанс контроллера, который внутри себя в том числе будет содержать код из ивентов

> Типа двусторонний биндинг?
Не вполне. Двусторонний точно делать не будем, об это уже все споткнулись и избегают. У нас будет классическая однонаправленная модель. 

Другое дело, что там же список элементов, и в каждом элементе еще бывает текст, статус прочитанности как минимум. Если делать сложно, то вот значит нужно рекурсивно собирать все поля, из них делать observable-сущность и на неё подписываться/отписываться. Но это прям сложновато. Вместо этого можно сделать вид, что мы работаем с одной observable-сущностью — списком. Будем отслеживать его изменение, которое включает изменение его длины и изменение его контента — айтема — (по id айтема)

2020-11-27 20:02 UTC, step-ponomarev commented on src/index.js
> +const addTaskFormView = new AddTaskFormView(onFormSubmit, onClickCompleteAll);
> Прокидывать инстанс контроллера, который внутри себя в том числе будет содержать код из ивентов

Вьюшка же не должна знать о контроллере.

2020-11-30 08:52 UTC, fromanywhere commented on src/index.js
> +const addTaskFormView = new AddTaskFormView(onFormSubmit, onClickCompleteAll);
Почему? А как иначе предлагается модифицировать стор от пользовательского ввода?

> Контроллер
Контроллер обеспечивает «связь» между пользователем и системой. Контролирует и направляет данные от пользователя к системе и наоборот. Использует модель и представление для реализации необходимого действия.

https://ru.wikipedia.org/wiki/Model-View-Controller

2020-12-06 12:06 UTC, merged